version: 2.1
jobs:
  build:
    docker:
      - image: "circleci/buildpack-deps:latest"
    steps:
      - checkout
      - run:
          name: Download Go
          command: |
            time curl -sfSLO https://dl.google.com/go/go1.14.1.linux-amd64.tar.gz
      - run:
          name: Download Chromium
          command: |
            time curl -sfSL "https://download-chromium.appspot.com/dl/Linux_x64?type=snapshots" -o chrome-linux.zip

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "5,20,35,50 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
