version: 2.1
jobs:
  build:
    docker:
      - image: "circleci/buildpack-deps:latest"
    steps:
      - checkout
      - run:
          name: Download Go
          command: |
            time curl -sSLO --retry 3 https://dl.google.com/go/go1.14.1.linux-amd64.tar.gz
      - run:
          name: Download Chromium
          command: |
            REVISION=$(curl -sSL --retry 5 "https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2FLAST_CHANGE?alt=media") \
            && time curl -sSL --retry 5 "https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F${REVISION}%2Fchrome-linux.zip?alt=media -o chrome-linux.zip"

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  scheduled-workflow:
    trggers:
      - schedule:
          cron: "*/15 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
